env:
    browser: true
    es6: true

extends:
    - airbnb-base
    - prettier
parserOptions:
    ecmaVersion: latest
    sourceType: module
rules:
    import/extensions: 0
    no-console: off
    indent: ['error', 4, { 'SwitchCase': 1 }]
    no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
